### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by tomasaschan** [shtik/Home#1]
Hi Mark! 👋 

I just listened to your latest episode on .NET Rocks, and Shtik - and the sentiments behind it - really resonated with me. Just this week I was looking around for a tool to solve this problem. I ended up dismissing Reveal.js for the same reasons you did, and using Remark.js instead, but I didn't find anything that was dead on what I'm looking for. Shtik sounds like it could really be That Thing.

In the interest of bringing it to 1.0, I'd love to see if I can contribute. I understood from the show that CSS and WebSockets are two pain points at the moment. I suck at CSS, but I have successfully built stuff with websockets... However, I found it a little difficult to figure out where to start. Is there a good place to start reading about architecture and such - how the different pieces fit together? Have you somewhere documented a usage scenario/test case/something like it that I could use to reproduce some of the issues you want help with, to see if I can fix them?

**Comment by MadsGF** [comment]
Hi Mark,

Like tlycken, I heard you on .NET Rocks, and want to help. I've been .NET'ing since 1.0, and built several apps on core. I'm also good in JS/TS, SPA stuff, and other client related stuff.
